### ISSUE TITLE
你好，请问下这个原理是什么吗？

### ISSUE THREAD

**Issue by Ryan0520** [susnmos/RevealLoader2#1]
你好，可以请问下这个原理是什么吗？每次升级，需要替换什么再重新打包吗？

**Comment by susnmos** [comment]
可以直接下载我的deb包，README理不是写的很清楚吗

susnm

2017年2月27日 +0800 PM2:16 CoderRyan <notifications@github.com>，写道：

**Comment by susnmos** [comment]
对的

susnm

2017年2月27日 +0800 PM3:27 CoderRyan <notifications@github.com>，写道：

**Comment by Ryan0520** [comment]
因为我现在的iOS系统是10.2，所以以前RevealLoader 已经没有用了，找了好久，都没有找到解决办法，然后试试在github上搜一下RevealLoader，就搜到你这个，装了一下，果然可以了。谢谢啊！
